import fs from 'node:fs'
import path from 'node:path'
import { kbPaths } from './paths.mjs'
import { DEFAULT_CONFIG } from './templates.mjs'
import { listWikiPages, isInvalidated } from './pages.mjs'

const WIKILINK_RE = /\[\[([^\]|#]+)(?:[#|][^\]]*)?\]\]/g

export function extractWikilinks(body) {
  const out = []
  for (const m of body.matchAll(WIKILINK_RE)) {
    const target = m[1].trim().replace(/\.md$/, '')
    if (!out.includes(target)) out.push(target)
  }
  return out
}

const SECTION_TITLES = { source: 'Sources', entity: 'Entities', concept: 'Concepts', comparison: 'Comparisons', other: 'Other' }

export function buildIndex(kbRoot) {
  const p = kbPaths(kbRoot)
  const cfg = fs.existsSync(p.config) ? { ...DEFAULT_CONFIG, ...JSON.parse(fs.readFileSync(p.config, 'utf8')) } : DEFAULT_CONFIG
  const pages = listWikiPages(kbRoot).filter(pg => !pg.error)

  // preserve pending section
  let pending = '## Pending concepts\n'
  if (fs.existsSync(p.indexMd)) {
    const m = fs.readFileSync(p.indexMd, 'utf8').match(/## Pending concepts[\s\S]*$/)
    if (m) pending = m[0].trimEnd() + '\n'
  }

  // `other` collects unknown types so index.md and graph.json agree on a page's bucket
  // (graph nodes still carry the raw type). Rendered as a final `## Other` section, only when non-empty.
  const byType = { source: [], entity: [], concept: [], comparison: [], other: [] }
  for (const pg of pages) (byType[pg.data.type] ?? byType.other).push(pg)
  const line = (pg) => {
    const base = `- [[${pg.relPath.replace(/\.md$/, '')}]] — ${pg.data.description ?? ''}`
    if (!isInvalidated(pg)) return base
    return pg.data.superseded_by
      ? `${base} ⚠ invalidated, superseded by [[${pg.data.superseded_by}]]`
      : `${base} ⚠ invalidated`
  }

  let indexBody = '# Index\n\n> Auto-generated by `llm-wiki index`. Only the "Pending concepts" section may be edited by the LLM.\n'
  const topicsSplit = pages.length > cfg.indexSplitAt
  if (topicsSplit) {
    fs.mkdirSync(p.topics, { recursive: true })
    for (const [type, list] of Object.entries(byType)) {
      if (!list.length) continue
      fs.writeFileSync(path.join(p.topics, `${type}.md`), `# ${SECTION_TITLES[type]}\n\n${list.map(line).join('\n')}\n`)
      indexBody += `\n## ${SECTION_TITLES[type]}\nSee [[topics/${type}]] (${list.length} pages)\n`
    }
  } else {
    for (const [type, list] of Object.entries(byType)) {
      if (type === 'other' && !list.length) continue
      indexBody += `\n## ${SECTION_TITLES[type]}\n${list.map(line).join('\n')}\n`
    }
  }
  fs.writeFileSync(p.indexMd, `${indexBody}\n${pending}`)

  const ids = new Set(pages.map(pg => pg.relPath.replace(/\.md$/, '')))
  const nodes = pages.map(pg => ({
    id: pg.relPath.replace(/\.md$/, ''),
    type: pg.data.type,
    title: pg.data.title,
    ...(isInvalidated(pg) ? { status: 'invalidated' } : {}),
  }))
  const edges = []
  for (const pg of pages) {
    const id = pg.relPath.replace(/\.md$/, '')
    for (const target of extractWikilinks(pg.body)) {
      if (ids.has(target)) edges.push({ source: id, target, type: 'wikilink' })
    }
    for (const src of pg.data.sources ?? []) edges.push({ source: id, target: String(src), type: 'source' })
    if (pg.data.superseded_by && ids.has(String(pg.data.superseded_by))) {
      edges.push({ source: id, target: String(pg.data.superseded_by), type: 'superseded_by' })
    }
  }
  fs.writeFileSync(p.graphJson, JSON.stringify({ nodes, edges }, null, 2) + '\n')

  const kbName = path.basename(path.resolve(kbRoot))
  const llms = [`# ${kbName}`, '', `> llm_wiki knowledge base. Read wiki/index.md first, then open full pages.`, '', '## Pages',
    ...pages.filter(pg => !isInvalidated(pg)).map(pg => `- [${pg.data.title}](wiki/${pg.relPath}): ${pg.data.description ?? ''}`)].join('\n') + '\n'
  fs.writeFileSync(p.llmsTxt, llms)

  return { pageCount: pages.length, topicsSplit }
}
