import fs from 'node:fs'
import path from 'node:path'
import { kbPaths } from './paths.mjs'
import { DEFAULT_CONFIG, agentsMdTemplate, readmeTemplate } from './templates.mjs'

const INDEX_SKELETON = `# Index

> Auto-generated by \`llm-wiki index\`. Only the "Pending concepts" section may be edited by the LLM.

## Sources

## Entities

## Concepts

## Comparisons

## Pending concepts
`

export function initKb(root) {
  const p = kbPaths(root)
  const created = []
  const skipped = []
  const dir = (d) => {
    if (fs.existsSync(d)) { skipped.push(d) } else { fs.mkdirSync(d, { recursive: true }); created.push(d) }
  }
  const file = (f, content) => {
    if (fs.existsSync(f)) { skipped.push(f) } else { fs.writeFileSync(f, content); created.push(f) }
  }
  dir(root)
  dir(p.raw)
  dir(p.sources); dir(p.entities); dir(p.concepts); dir(p.comparisons)
  const { linkStyle, ...emittedConfig } = DEFAULT_CONFIG
  file(p.config, JSON.stringify(emittedConfig, null, 2) + '\n')
  file(p.schemaFile, agentsMdTemplate(DEFAULT_CONFIG))
  file(p.readme, readmeTemplate(path.basename(path.resolve(root))))
  file(p.manifest, JSON.stringify({ files: {} }, null, 2) + '\n')
  file(p.indexMd, INDEX_SKELETON)
  file(p.logMd, '# Log\n')
  file(p.hotMd, '# Hot\n\n(recent activity snapshot, maintained by the LLM, ~500 chars)\n')
  return { created, skipped }
}
